#!/bin/python
from laintracker import *

synth = Synth()
parser = Parser(name="Intensive Care Unit", filename="icu.json", default_wave="square")

#parser.editInstrument(pattern="01", wavetype="sawtooth", envelope={"type": "wave", "args": {"wavetype": "sine", "length": 1, "frequency": 1}})

parser.editInstrument(pattern=["01", "12"], wavetype="sawtooth", envelope={"type": "linear_decay", "args": {"length": 1}})
parser.editInstrument(pattern="14", wavetype="triangle")
parser.editInstrument(pattern="10", wavetype="sample", amplitude=2)

parser.editOrder(["01"])
for i in range(0,10):
    parser.editOrder(["02"])
for i in range(0,9):
    parser.editOrder(["03"])
for i in range(0,10):
    parser.editOrder(["04"])
for i in range(0,9):
    parser.editOrder(["05"])
parser.editOrder(["10"])
for i in range(0,3):
    parser.editOrder(["06"])
parser.editOrder(["07"])
for i in range(0,3):
    parser.editOrder(["06"])
parser.editOrder(["07"])


parser.editOrder(["06","08"])
parser.editOrder(["06"])
parser.editOrder(["06", "09"])
parser.editOrder(["07"])
parser.editOrder(["06","08"])
parser.editOrder(["06"])
parser.editOrder(["06", "09"])

parser.editOrder(["10"])

parser.editOrder(["11", "12"])
parser.editOrder(["11", "12"])

parser.editOrder(["13", "12"])
parser.editOrder(["13", "14", "12"])
parser.editOrder(["13", "14", "12"])
parser.editOrder(["13", "14", "12"])
parser.editOrder(["13", "14", "12"])
#parser.editOrder(["13", "14", "12"])
parser.editOrder(["13", "14", "15", "12"])

parser.editOrder(["10"])

parser.editOrder(["06","08"])
parser.editOrder(["06"])
parser.editOrder(["06", "09"])
parser.editOrder(["07"])
parser.editOrder(["06","08"])
parser.editOrder(["06"])
parser.editOrder(["06", "09"])

parser.editOrder(["10"])


parser.editPattern(pattern="01", note=["C#5", "A4", "E5"], length=1.28)
parser.editPattern(pattern="01", note=["B4", "G#4", "E4"])
parser.editPattern(pattern="01", note=["C#5", "A4", "F#4"])
parser.editPattern(pattern="01", note=["A4", "F#4", "D4"])

parser.editPattern(pattern="12", note=["C#5", "A4", "E5"], length=2.56)
#parser.editPattern(pattern="12", note="", length=1.28)
parser.editPattern(pattern="12", note=["B4", "G#4", "E4"], length=2.56)
#parser.editPattern(pattern="12", note="", length=1.28)
parser.editPattern(pattern="12", note=["C#5", "A4", "F#4"], length=2.56)
#parser.editPattern(pattern="12", note="", length=1.28)
parser.editPattern(pattern="12", note=["A4", "F#4", "D4"], length=2.56)
#parser.editPattern(pattern="12", note="", length=1.28)

parser.editPattern(pattern="02", note="A4", length=0.1)
parser.editPattern(pattern="02", note="E5")
parser.editPattern(pattern="02", note="A5")

parser.editPattern(pattern="03", note="B4")
parser.editPattern(pattern="03", note="E5")
parser.editPattern(pattern="03", note="E4")

parser.editPattern(pattern="04", note="F#4")
parser.editPattern(pattern="04", note="C#5")
parser.editPattern(pattern="04", note="F#5")

parser.editPattern(pattern="05", note="A4")
parser.editPattern(pattern="05", note="D5")
parser.editPattern(pattern="05", note="D4")

parser.editPattern(pattern="06", note="A3", length=0.08)
parser.editPattern(pattern="06", note="", length=0.24)
parser.editPattern(pattern="06", note="A4", length=0.08)
parser.editPattern(pattern="06", note="")
parser.editPattern(pattern="06", note="A3")
parser.editPattern(pattern="06", note="")
parser.editPattern(pattern="06", note="E4")
parser.editPattern(pattern="06", note="")
parser.editPattern(pattern="06", note="A4")
parser.editPattern(pattern="06", note="")
parser.editPattern(pattern="06", note="A4")
parser.editPattern(pattern="06", note="")
parser.editPattern(pattern="06", note="A3")
parser.editPattern(pattern="06", note="")

parser.editPattern(pattern="07", note="A4")
parser.editPattern(pattern="07", note="")
parser.editPattern(pattern="07", note="A3")
parser.editPattern(pattern="07", note="")
parser.editPattern(pattern="07", note="A3")
parser.editPattern(pattern="07", note="")
parser.editPattern(pattern="07", note="A4")
parser.editPattern(pattern="07", note="")
parser.editPattern(pattern="07", note="A3")
parser.editPattern(pattern="07", note="")
parser.editPattern(pattern="07", note="A3")
parser.editPattern(pattern="07", note="")
parser.editPattern(pattern="07", note="D5")
parser.editPattern(pattern="07", note="")
parser.editPattern(pattern="07", note="C#5")
parser.editPattern(pattern="07", note="")

parser.editPattern(pattern="08", note="E6", length=0.08)
parser.editPattern(pattern="08", note="", length=0.24)
parser.editPattern(pattern="08", note="A5", length=0.08)
parser.editPattern(pattern="08", note="", length=0.24)
parser.editPattern(pattern="08", note="D6", length=0.08)
parser.editPattern(pattern="08", note="")
parser.editPattern(pattern="08", note="C#6")
parser.editPattern(pattern="08", note="")
parser.editPattern(pattern="08", note="E6")
parser.editPattern(pattern="08", note="")
parser.editPattern(pattern="08", note="A5")
parser.editPattern(pattern="08", note="")

parser.editPattern(pattern="09", note="D6", length=0.08)
parser.editPattern(pattern="09", note="", length=0.24)
parser.editPattern(pattern="09", note="C#6", length=0.08)
parser.editPattern(pattern="09", note="", length=0.24)
parser.editPattern(pattern="09", note="B5", length=0.08)
parser.editPattern(pattern="09", note="")
parser.editPattern(pattern="09", note="A5")
parser.editPattern(pattern="09", note="")
parser.editPattern(pattern="09", note="D6")
parser.editPattern(pattern="09", note="")
parser.editPattern(pattern="09", note="C#6")
parser.editPattern(pattern="09", note="")

# parser.editPattern(pattern="10", note="A3", length=0.08)
# parser.editPattern(pattern="10", note="", length=0.24)
# parser.editPattern(pattern="10", note="A3", length=0.08)
# parser.editPattern(pattern="10", note="", length=0.24)
# parser.editPattern(pattern="10", note="A3", length=0.08)
# parser.editPattern(pattern="10", note="", length=0.24)
# parser.editPattern(pattern="10", note="G3", length=0.08)
# parser.editPattern(pattern="10", note="", length=0.24)
parser.editPattern(pattern="10", file="crash1.wav", cut=(0,0.2), length=1)
parser.editPattern(pattern="10", file="", length=0.1)
parser.editPattern(pattern="10", file="crash1.wav", length=1)
parser.editPattern(pattern="10", file="", length=0.1)
parser.editPattern(pattern="10", file="crash1.wav", length=1)
parser.editPattern(pattern="10", file="", length=0.1)
parser.editPattern(pattern="10", file="crash2.wav", cut=(0,0.2), length=1)
parser.editPattern(pattern="10", file="", length=0.1)


parser.editPattern(pattern="11", note="A3", length=0.16)
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="E4")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="E4")
parser.editPattern(pattern="11", note="A3")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="A3")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="A3")
parser.editPattern(pattern="11", note="E4")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="E4")
parser.editPattern(pattern="11", note="A3")
parser.editPattern(pattern="11", note="C#5")
parser.editPattern(pattern="11", note="A4")
parser.editPattern(pattern="11", note="B4")# !
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="E3")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="E4")
parser.editPattern(pattern="11", note="E3")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="B4")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="A4")
parser.editPattern(pattern="11", note="G#4")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="B4")
parser.editPattern(pattern="11", note="E4")
parser.editPattern(pattern="11", note="G#4")
parser.editPattern(pattern="11", note="B4")
parser.editPattern(pattern="11", note="A4") # !
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="F#3")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="F#4")
parser.editPattern(pattern="11", note="A4")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="F#3")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="D5")
parser.editPattern(pattern="11", note="C#5")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="A4")
parser.editPattern(pattern="11", note="C#5")
parser.editPattern(pattern="11", note="D5")
parser.editPattern(pattern="11", note="C#5")
parser.editPattern(pattern="11", note="A4") # !
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="D3")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="F#4")
parser.editPattern(pattern="11", note="A4")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="D3")
parser.editPattern(pattern="11", note="")
parser.editPattern(pattern="11", note="D5")
parser.editPattern(pattern="11", note="C#5")
parser.editPattern(pattern="11", note="A4")
parser.editPattern(pattern="11", note="B4")
parser.editPattern(pattern="11", note="D5")
parser.editPattern(pattern="11", note="C#5")
parser.editPattern(pattern="11", note="A4") # !

parser.editPattern(pattern="13", note="A3")
parser.editPattern(pattern="13", note="E4")
parser.editPattern(pattern="13", note="A4")
parser.editPattern(pattern="13", note="A3")
parser.editPattern(pattern="13", note="E4")
parser.editPattern(pattern="13", note="A4")
parser.editPattern(pattern="13", note="A3")
parser.editPattern(pattern="13", note="E4")
parser.editPattern(pattern="13", note="A3")
parser.editPattern(pattern="13", note="A4")
parser.editPattern(pattern="13", note="E4")
parser.editPattern(pattern="13", note="A4")
parser.editPattern(pattern="13", note="A3")
parser.editPattern(pattern="13", note="B4")
parser.editPattern(pattern="13", note="C#5")
parser.editPattern(pattern="13", note="E5")
parser.editPattern(pattern="13", note="E3")
parser.editPattern(pattern="13", note="B3")
parser.editPattern(pattern="13", note="E4")
parser.editPattern(pattern="13", note="E3")
parser.editPattern(pattern="13", note="B3")
parser.editPattern(pattern="13", note="E4")
parser.editPattern(pattern="13", note="E3")
parser.editPattern(pattern="13", note="B3")
parser.editPattern(pattern="13", note="E4")
parser.editPattern(pattern="13", note="F#4")
parser.editPattern(pattern="13", note="B3")
parser.editPattern(pattern="13", note="G#4")
parser.editPattern(pattern="13", note="B3")
parser.editPattern(pattern="13", note="G#4")
parser.editPattern(pattern="13", note="C#5")
parser.editPattern(pattern="13", note="F#4")
parser.editPattern(pattern="13", note="F#3")
parser.editPattern(pattern="13", note="C#4")
parser.editPattern(pattern="13", note="F#4")
parser.editPattern(pattern="13", note="F#3")
parser.editPattern(pattern="13", note="C#4")
parser.editPattern(pattern="13", note="F#4")
parser.editPattern(pattern="13", note="F#3")
parser.editPattern(pattern="13", note="C#4")
parser.editPattern(pattern="13", note="G#4")
parser.editPattern(pattern="13", note="F#3")
parser.editPattern(pattern="13", note="A4")
parser.editPattern(pattern="13", note="F#3")
parser.editPattern(pattern="13", note="F#4")
parser.editPattern(pattern="13", note="F#3")
parser.editPattern(pattern="13", note="D5")
parser.editPattern(pattern="13", note="C#5")
parser.editPattern(pattern="13", note="D3")
parser.editPattern(pattern="13", note="A3")
parser.editPattern(pattern="13", note="D4")
parser.editPattern(pattern="13", note="D3")
parser.editPattern(pattern="13", note="A3")
parser.editPattern(pattern="13", note="D4")
parser.editPattern(pattern="13", note="D3")
parser.editPattern(pattern="13", note="A3")
parser.editPattern(pattern="13", note="D5")
parser.editPattern(pattern="13", note="D3")
parser.editPattern(pattern="13", note="C#5")
parser.editPattern(pattern="13", note="D3")
parser.editPattern(pattern="13", note="A4")
parser.editPattern(pattern="13", note="D3")
parser.editPattern(pattern="13", note="A4")
parser.editPattern(pattern="13", note="C#5")

parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="C#6")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="B5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="B5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="B5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="B5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="B5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="C#6")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="B5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="A5")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="")
parser.editPattern(pattern="14", note="B5")
parser.editPattern(pattern="14", note="")

parser.editPattern(pattern="15", note="", length=0.08)
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="A5")
parser.editPattern(pattern="15", note="A4")
parser.editPattern(pattern="15", note="")
parser.editPattern(pattern="15", note="A5")
parser.editPattern(pattern="15", note="")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="")
parser.editPattern(pattern="15", note="A4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="A5")
parser.editPattern(pattern="15", note="")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="A5")
parser.editPattern(pattern="15", note="A4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="A5")
parser.editPattern(pattern="15", note="")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="A5")
parser.editPattern(pattern="15", note="A4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="A5")
parser.editPattern(pattern="15", note="A4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="A5")
parser.editPattern(pattern="15", note="A4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="A5")
parser.editPattern(pattern="15", note="A4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="A5")
parser.editPattern(pattern="15", note="B4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="E4")
parser.editPattern(pattern="15", note="B4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="")
parser.editPattern(pattern="15", note="B4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="E4")
parser.editPattern(pattern="15", note="B4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="")
parser.editPattern(pattern="15", note="B4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="E4")
parser.editPattern(pattern="15", note="B4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="E4")
parser.editPattern(pattern="15", note="B4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="E4")
parser.editPattern(pattern="15", note="B4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="E4")
parser.editPattern(pattern="15", note="B4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="E4")
parser.editPattern(pattern="15", note="B4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="E4")
parser.editPattern(pattern="15", note="B4")
parser.editPattern(pattern="15", note="E5")
parser.editPattern(pattern="15", note="C#5")
parser.editPattern(pattern="15", note="F#5")
parser.editPattern(pattern="15", note="F#4")
parser.editPattern(pattern="15", note="C#5")
parser.editPattern(pattern="15", note="F#5")
parser.editPattern(pattern="15", note="")
parser.editPattern(pattern="15", note="C#5")
parser.editPattern(pattern="15", note="F#5")
parser.editPattern(pattern="15", note="F#4")
parser.editPattern(pattern="15", note="C#5")
parser.editPattern(pattern="15", note="F#5")
parser.editPattern(pattern="15", note="")
parser.editPattern(pattern="15", note="C#5")
parser.editPattern(pattern="15", note="F#5")
parser.editPattern(pattern="15", note="F#4")
parser.editPattern(pattern="15", note="C#5")
parser.editPattern(pattern="15", note="F#5")
parser.editPattern(pattern="15", note="F#4")
parser.editPattern(pattern="15", note="C#5")
parser.editPattern(pattern="15", note="F#5")
parser.editPattern(pattern="15", note="F#4")
parser.editPattern(pattern="15", note="C#5")
parser.editPattern(pattern="15", note="F#5")
parser.editPattern(pattern="15", note="")
parser.editPattern(pattern="15", note="C#5")
parser.editPattern(pattern="15", note="F#5")
parser.editPattern(pattern="15", note="F#4")
parser.editPattern(pattern="15", note="C#5")
parser.editPattern(pattern="15", note="F#5")
parser.editPattern(pattern="15", note="F#4")
parser.editPattern(pattern="15", note="C#5")
parser.editPattern(pattern="15", note="F#5")
parser.editPattern(pattern="15", note="A4")
parser.editPattern(pattern="15", note="D5")
parser.editPattern(pattern="15", note="D4")
parser.editPattern(pattern="15", note="A4")
parser.editPattern(pattern="15", note="D5")
parser.editPattern(pattern="15", note="")
parser.editPattern(pattern="15", note="A4")
parser.editPattern(pattern="15", note="D5")
parser.editPattern(pattern="15", note="D4")
parser.editPattern(pattern="15", note="A4")
parser.editPattern(pattern="15", note="D5")
parser.editPattern(pattern="15", note="")
parser.editPattern(pattern="15", note="A4")
parser.editPattern(pattern="15", note="D5")
parser.editPattern(pattern="15", note="D4")

data = parser.getData()

synth.compile(data, verbose=True)
